import { join } from "node:path";
import { registerDetector } from "../registry.js";
import { ensureLevel } from "../fs/paths.js";
import type { Detector, Finding } from "../types.js";

/**
 * xcode-derived-data — Xcode's per-project build cache.
 *
 * `~/Library/Developer/Xcode/DerivedData` holds build products, indexes, and
 * module caches — all regenerable by rebuilding. Safe to remove; the cost is a
 * slower next build (and a fresh index).
 *
 * NOTE: `~/Library/Developer/Xcode/Archives` is a DIFFERENT, review-level
 * finding (real shippable .xcarchives, not a cache) — that lands in RS8. This
 * detector is DerivedData only.
 */
export const xcodeDerivedData: Detector = {
  id: "xcode-derived-data",
  title: "Xcode DerivedData",
  cost: "fast",
  async scan(ctx): Promise<Finding[]> {
    const path = join(ctx.home, "Library/Developer/Xcode/DerivedData");
    if (!(await ctx.pathExists(path))) return [];

    const size = await ctx.dirSize(path);
    if (!size.unknown && size.diskBytes === 0) return []; // empty — nothing to report

    const lu = await ctx.lastUsed(path);

    return [
      {
        id: "xcode-derived-data",
        detector: "xcode-derived-data",
        title: "Xcode DerivedData (build cache)",
        paths: [path],
        sizeBytes: size.unknown ? 0 : size.diskBytes,
        apparentSizeBytes: size.unknown ? undefined : size.apparentBytes,
        level: ensureLevel(path, "safe"),
        lastUsedAt: lu.at,
        lastUsedSource: lu.source,
        whatItIs:
          "Xcode's per-project build cache — compiled build products, indexes, and module " +
          "caches. Everything here is regenerated by rebuilding; none of it is source or config.",
        ifRemoved:
          "Nothing breaks. Your next build for each project recreates its DerivedData; the " +
          "first build after is slower and the code index rebuilds.",
        dependents: ["Incremental build speed (next build is a clean build)", "Xcode's symbol index"],
        reversible: {
          possible: true,
          how: "Rebuilt on the next Xcode build (Product ▸ Build)",
        },
        reclaim: {
          command: `rm -rf "${path}"`,
          requiresSudo: false,
          kind: "delete",
        },
      },
    ];
  },
};

registerDetector(xcodeDerivedData);
